# Generated by Django 5.0.7 on 2024-07-22 15:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=50)),
                ('statement_description', models.TextField(max_length=2000)),
                ('base_function_code', models.CharField(max_length=100, unique=True)),
                ('problem_visualization_illustration', models.ImageField(upload_to='images/problems')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(blank=True, choices=[('Hard', 'Hard'), ('Easy', 'Easy'), ('Medium', 'Medium')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemConstraints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_description', models.CharField(max_length=100)),
                ('time_limit', models.PositiveBigIntegerField()),
                ('memory_limit', models.PositiveBigIntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_judge.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('C++', 'C++'), ('Python', 'Python')], max_length=20)),
                ('verdict', models.CharField(max_length=50)),
                ('compiler_output', models.TextField(max_length=500)),
                ('test_case_results', models.JSONField()),
                ('submitted_code', models.TextField(max_length=10000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('memory_used', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_judge.problems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_judge.problems')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_judge.problems')),
            ],
        ),
    ]
