# Generated by Django 5.0.7 on 2024-07-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_visualization_illustration',
            field=models.ImageField(blank=True, null=True, upload_to='images/problems'),
        ),
    ]
