# Generated by Django 5.0.7 on 2024-07-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0003_problems_constraint_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='language',
            field=models.CharField(blank=True, choices=[('C++', 'C++'), ('Python', 'Python')], max_length=20),
        ),
        migrations.AlterField(
            model_name='problems',
            name='base_function_code',
            field=models.JSONField(default=dict),
        ),
    ]
