# Generated by Django 5.0.7 on 2024-07-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0004_problems_language_alter_problems_base_function_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='compiler_output',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(max_length=255),
        ),
    ]
