# Generated by Django 5.0.7 on 2024-07-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0005_alter_problems_problem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='compiler_output',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_code',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.TextField(),
        ),
    ]
