# Generated by Django 5.0.7 on 2024-07-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0006_alter_submission_compiler_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='base_function_code',
        ),
    ]
