# Generated by Django 5.0.7 on 2024-07-23 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_judge', '0007_remove_problems_base_function_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='execution_time',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory_used',
            field=models.BigIntegerField(),
        ),
    ]
